---
title: Swell Tracker
author: 'Gabe Mednick'
date: '2020-12-22'
slug: santa-cruz-surf-report
categories: []
tags: []
subtitle: ''
summary: "This app provides the most recent data from NOAA's wave model <br> (Pacific) and buoy data near Santa Cruz, California"
authors: []
lastmod: '2020-12-22T11:33:04-08:00'
featured: no
image: 
  caption: '[The Lane](steamer-lane.jpg)'
  focal_point: ''
  preview_only: no
projects: []
runtime: 'shiny'
---

#### As a life-long surfer, building this app was like putting my finger on the pulse of the ocean..pure joy! The app uses data from NOAA's wave model (WWIII) and buoy data near Santa Cruz (buoyid = 46042) to report on the live surf and wind conditions. You can open the app with this [link](https://biolight-informatics.shinyapps.io/surf_reporter/) or explore it below. The data is loaded into R using the `rnoaa` and `rNOMADS` packages.  

#### In future versions of this app, I plan to animate the wave model data. I would also like to add features that give the user more control (i.e., be able to select regions and buoys) and possibly create a predictive long-range model. This app is currently limited by the slow nature of data retrieval from NOAA. To prevent it from timing out before loading, I have a separate script for extracting the data, filtering it down, then saving the results to file. I am using a scheduling manager (Cron) to automate this process but, unfortunately, this only updates the files on my computer so I have to redeploy the app in order to display the most recent data (this sort of defeats the purpose of live data). I am currently in the process of figuring out how to automate this process using google sheets and the googlesheets4 package in R. My code is available on [Git<i class="fab fa-github"  style="color: #FFCC00"></i>hub](https://github.com/gmednick/surf-watch/blob/master/app.R).

#### Please note the app takes a minute to load.

<iframe height="800" width="100%" frameborder="no" src="https://biolight-informatics.shinyapps.io/surf_reporter/"> </iframe>